### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by waveiron** [mpetrunic/fastify-sse-v2#70]
```
TypeError: Cannot read properties of undefined (reading 'source')
    at _Reply.sse (/Users/kev/code_base/instinctmethod/server/node_modules/fastify-sse-v2/lib/plugin.js:41:33)
    at IncomingMessage.<anonymous> (file:///Users/kev/code_base/instinctmethod/server/src/route.ts:200:15)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at IncomingMessage.Readable.read (node:internal/streams/readable:539:10)
    at flow (node:internal/streams/readable:1023:34)
    at emitReadable_ (node:internal/streams/readable:604:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

Complete code:

```typescript
  void server.post('/call/gpt_message/send_stream', {}, async (i: FastifyRequest, o: FastifyReply) => {
      const opt = i.input();
      const row = await gpt_message_ensure(opt, i);
      const stream = (await Gpt_message.send(row.id, true));
      stream.on('data', (chunk: any) => {
        const payloads = chunk.toString().split('\n\n');
        for (const payload of payloads) {
          if (payload.includes('[DONE]')) return;
          let content: string | undefined;
          if (payload.startsWith('data:')) {
            try {
              const json = JSON.parse(payload.replace('data: ', ''));
              content = json.choices[0].delta?.content;
            } catch (error) {
              console.log(chunk.toString());
              console.log(`Error with JSON.parse and ${payload}.\n${error}`);
            }
          }

          if (content) {
            o.sse({ id: '1', data: chunk } as any); // this line throws
          }
        }
      });

      stream.on('end', () => {
        setTimeout(() => {
          console.log('\nStream done');
          o.send({ message: 'Stream done' });
        }, 10);
      });

      stream.on('error', (err: Error) => {
        console.log(err);
        o.send(err);
      });

    },
  )
```

**Comment by mpetrunic** [comment]
This is obviously a bug and I'll fix it. But for you fix will most likely just bring better error messages. My guess is that by the time you send first sse event, fastify already sents headers.


Could you try adding ass first like `o.sse({ retry: options.retryDelay || 3000 })`
